// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPullRequestRepository creates a new instance of MockPullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type MockPullRequestRepository struct {
	mock.Mock
}

type MockPullRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestRepository) EXPECT() *MockPullRequestRepository_Expecter {
	return &MockPullRequestRepository_Expecter{mock: &_m.Mock}
}

// CreatePR provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) CreatePR(ctx context.Context, pr *model.PullRequest) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PullRequest) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockPullRequestRepository_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *model.PullRequest
func (_e *MockPullRequestRepository_Expecter) CreatePR(ctx interface{}, pr interface{}) *MockPullRequestRepository_CreatePR_Call {
	return &MockPullRequestRepository_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, pr)}
}

func (_c *MockPullRequestRepository_CreatePR_Call) Run(run func(ctx context.Context, pr *model.PullRequest)) *MockPullRequestRepository_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.PullRequest
		if args[1] != nil {
			arg1 = args[1].(*model.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_CreatePR_Call) Return(err error) *MockPullRequestRepository_CreatePR_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_CreatePR_Call) RunAndReturn(run func(ctx context.Context, pr *model.PullRequest) error) *MockPullRequestRepository_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePRReviewers provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) CreatePRReviewers(ctx context.Context, pr *model.PullRequest) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePRReviewers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PullRequest) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_CreatePRReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePRReviewers'
type MockPullRequestRepository_CreatePRReviewers_Call struct {
	*mock.Call
}

// CreatePRReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *model.PullRequest
func (_e *MockPullRequestRepository_Expecter) CreatePRReviewers(ctx interface{}, pr interface{}) *MockPullRequestRepository_CreatePRReviewers_Call {
	return &MockPullRequestRepository_CreatePRReviewers_Call{Call: _e.mock.On("CreatePRReviewers", ctx, pr)}
}

func (_c *MockPullRequestRepository_CreatePRReviewers_Call) Run(run func(ctx context.Context, pr *model.PullRequest)) *MockPullRequestRepository_CreatePRReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.PullRequest
		if args[1] != nil {
			arg1 = args[1].(*model.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_CreatePRReviewers_Call) Return(err error) *MockPullRequestRepository_CreatePRReviewers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_CreatePRReviewers_Call) RunAndReturn(run func(ctx context.Context, pr *model.PullRequest) error) *MockPullRequestRepository_CreatePRReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.PullRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.PullRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.PullRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPullRequestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPullRequestRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockPullRequestRepository_GetByID_Call {
	return &MockPullRequestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPullRequestRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPullRequestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetByID_Call) Return(pullRequest *model.PullRequest, err error) *MockPullRequestRepository_GetByID_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.PullRequest, error)) *MockPullRequestRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReviewer provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetByReviewer(ctx context.Context, userID uuid.UUID) ([]*model.PullRequestShort, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewer")
	}

	var r0 []*model.PullRequestShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.PullRequestShort, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.PullRequestShort); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PullRequestShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReviewer'
type MockPullRequestRepository_GetByReviewer_Call struct {
	*mock.Call
}

// GetByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPullRequestRepository_Expecter) GetByReviewer(ctx interface{}, userID interface{}) *MockPullRequestRepository_GetByReviewer_Call {
	return &MockPullRequestRepository_GetByReviewer_Call{Call: _e.mock.On("GetByReviewer", ctx, userID)}
}

func (_c *MockPullRequestRepository_GetByReviewer_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPullRequestRepository_GetByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetByReviewer_Call) Return(pullRequestShorts []*model.PullRequestShort, err error) *MockPullRequestRepository_GetByReviewer_Call {
	_c.Call.Return(pullRequestShorts, err)
	return _c
}

func (_c *MockPullRequestRepository_GetByReviewer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*model.PullRequestShort, error)) *MockPullRequestRepository_GetByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// GetViewers provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetViewers(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetViewers")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetViewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetViewers'
type MockPullRequestRepository_GetViewers_Call struct {
	*mock.Call
}

// GetViewers is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPullRequestRepository_Expecter) GetViewers(ctx interface{}, id interface{}) *MockPullRequestRepository_GetViewers_Call {
	return &MockPullRequestRepository_GetViewers_Call{Call: _e.mock.On("GetViewers", ctx, id)}
}

func (_c *MockPullRequestRepository_GetViewers_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPullRequestRepository_GetViewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetViewers_Call) Return(uUIDs []uuid.UUID, err error) *MockPullRequestRepository_GetViewers_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockPullRequestRepository_GetViewers_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)) *MockPullRequestRepository_GetViewers_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) Merge(ctx context.Context, id uuid.UUID) (*model.PullRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 *model.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.PullRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.PullRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockPullRequestRepository_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPullRequestRepository_Expecter) Merge(ctx interface{}, id interface{}) *MockPullRequestRepository_Merge_Call {
	return &MockPullRequestRepository_Merge_Call{Call: _e.mock.On("Merge", ctx, id)}
}

func (_c *MockPullRequestRepository_Merge_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPullRequestRepository_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_Merge_Call) Return(pullRequest *model.PullRequest, err error) *MockPullRequestRepository_Merge_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_Merge_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.PullRequest, error)) *MockPullRequestRepository_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewers provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) ReassignReviewers(ctx context.Context, prID uuid.UUID, oldID uuid.UUID, newID uuid.UUID) error {
	ret := _mock.Called(ctx, prID, oldID, newID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, prID, oldID, newID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_ReassignReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewers'
type MockPullRequestRepository_ReassignReviewers_Call struct {
	*mock.Call
}

// ReassignReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID uuid.UUID
//   - oldID uuid.UUID
//   - newID uuid.UUID
func (_e *MockPullRequestRepository_Expecter) ReassignReviewers(ctx interface{}, prID interface{}, oldID interface{}, newID interface{}) *MockPullRequestRepository_ReassignReviewers_Call {
	return &MockPullRequestRepository_ReassignReviewers_Call{Call: _e.mock.On("ReassignReviewers", ctx, prID, oldID, newID)}
}

func (_c *MockPullRequestRepository_ReassignReviewers_Call) Run(run func(ctx context.Context, prID uuid.UUID, oldID uuid.UUID, newID uuid.UUID)) *MockPullRequestRepository_ReassignReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_ReassignReviewers_Call) Return(err error) *MockPullRequestRepository_ReassignReviewers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_ReassignReviewers_Call) RunAndReturn(run func(ctx context.Context, prID uuid.UUID, oldID uuid.UUID, newID uuid.UUID) error) *MockPullRequestRepository_ReassignReviewers_Call {
	_c.Call.Return(run)
	return _c
}
