// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPullRequestService creates a new instance of MockPullRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestService {
	mock := &MockPullRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullRequestService is an autogenerated mock type for the PullRequestService type
type MockPullRequestService struct {
	mock.Mock
}

type MockPullRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestService) EXPECT() *MockPullRequestService_Expecter {
	return &MockPullRequestService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) Create(ctx context.Context, p *model.PullRequestShort) (*model.PullRequest, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PullRequestShort) (*model.PullRequest, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PullRequestShort) *model.PullRequest); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.PullRequestShort) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPullRequestService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *model.PullRequestShort
func (_e *MockPullRequestService_Expecter) Create(ctx interface{}, p interface{}) *MockPullRequestService_Create_Call {
	return &MockPullRequestService_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockPullRequestService_Create_Call) Run(run func(ctx context.Context, p *model.PullRequestShort)) *MockPullRequestService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.PullRequestShort
		if args[1] != nil {
			arg1 = args[1].(*model.PullRequestShort)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestService_Create_Call) Return(pullRequest *model.PullRequest, err error) *MockPullRequestService_Create_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestService_Create_Call) RunAndReturn(run func(ctx context.Context, p *model.PullRequestShort) (*model.PullRequest, error)) *MockPullRequestService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReviewer provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) GetByReviewer(ctx context.Context, userID uuid.UUID) ([]*model.PullRequestShort, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewer")
	}

	var r0 []*model.PullRequestShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.PullRequestShort, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.PullRequestShort); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PullRequestShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestService_GetByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReviewer'
type MockPullRequestService_GetByReviewer_Call struct {
	*mock.Call
}

// GetByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPullRequestService_Expecter) GetByReviewer(ctx interface{}, userID interface{}) *MockPullRequestService_GetByReviewer_Call {
	return &MockPullRequestService_GetByReviewer_Call{Call: _e.mock.On("GetByReviewer", ctx, userID)}
}

func (_c *MockPullRequestService_GetByReviewer_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPullRequestService_GetByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestService_GetByReviewer_Call) Return(pullRequestShorts []*model.PullRequestShort, err error) *MockPullRequestService_GetByReviewer_Call {
	_c.Call.Return(pullRequestShorts, err)
	return _c
}

func (_c *MockPullRequestService_GetByReviewer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*model.PullRequestShort, error)) *MockPullRequestService_GetByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) Merge(ctx context.Context, id uuid.UUID) (*model.PullRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 *model.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.PullRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.PullRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestService_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockPullRequestService_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPullRequestService_Expecter) Merge(ctx interface{}, id interface{}) *MockPullRequestService_Merge_Call {
	return &MockPullRequestService_Merge_Call{Call: _e.mock.On("Merge", ctx, id)}
}

func (_c *MockPullRequestService_Merge_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPullRequestService_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestService_Merge_Call) Return(pullRequest *model.PullRequest, err error) *MockPullRequestService_Merge_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestService_Merge_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.PullRequest, error)) *MockPullRequestService_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewers provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) ReassignReviewers(ctx context.Context, oldID uuid.UUID, prID uuid.UUID) (*model.PullRequest, uuid.UUID, error) {
	ret := _mock.Called(ctx, oldID, prID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewers")
	}

	var r0 *model.PullRequest
	var r1 uuid.UUID
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.PullRequest, uuid.UUID, error)); ok {
		return returnFunc(ctx, oldID, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.PullRequest); ok {
		r0 = returnFunc(ctx, oldID, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) uuid.UUID); ok {
		r1 = returnFunc(ctx, oldID, prID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, oldID, prID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPullRequestService_ReassignReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewers'
type MockPullRequestService_ReassignReviewers_Call struct {
	*mock.Call
}

// ReassignReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - oldID uuid.UUID
//   - prID uuid.UUID
func (_e *MockPullRequestService_Expecter) ReassignReviewers(ctx interface{}, oldID interface{}, prID interface{}) *MockPullRequestService_ReassignReviewers_Call {
	return &MockPullRequestService_ReassignReviewers_Call{Call: _e.mock.On("ReassignReviewers", ctx, oldID, prID)}
}

func (_c *MockPullRequestService_ReassignReviewers_Call) Run(run func(ctx context.Context, oldID uuid.UUID, prID uuid.UUID)) *MockPullRequestService_ReassignReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestService_ReassignReviewers_Call) Return(pullRequest *model.PullRequest, uUID uuid.UUID, err error) *MockPullRequestService_ReassignReviewers_Call {
	_c.Call.Return(pullRequest, uUID, err)
	return _c
}

func (_c *MockPullRequestService_ReassignReviewers_Call) RunAndReturn(run func(ctx context.Context, oldID uuid.UUID, prID uuid.UUID) (*model.PullRequest, uuid.UUID, error)) *MockPullRequestService_ReassignReviewers_Call {
	_c.Call.Return(run)
	return _c
}
