// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatisticsRepository creates a new instance of MockStatisticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatisticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatisticsRepository {
	mock := &MockStatisticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatisticsRepository is an autogenerated mock type for the StatisticsRepository type
type MockStatisticsRepository struct {
	mock.Mock
}

type MockStatisticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatisticsRepository) EXPECT() *MockStatisticsRepository_Expecter {
	return &MockStatisticsRepository_Expecter{mock: &_m.Mock}
}

// GetPRStatistics provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetPRStatistics(ctx context.Context) ([]*model.PRStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPRStatistics")
	}

	var r0 []*model.PRStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.PRStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.PRStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PRStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetPRStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRStatistics'
type MockStatisticsRepository_GetPRStatistics_Call struct {
	*mock.Call
}

// GetPRStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatisticsRepository_Expecter) GetPRStatistics(ctx interface{}) *MockStatisticsRepository_GetPRStatistics_Call {
	return &MockStatisticsRepository_GetPRStatistics_Call{Call: _e.mock.On("GetPRStatistics", ctx)}
}

func (_c *MockStatisticsRepository_GetPRStatistics_Call) Run(run func(ctx context.Context)) *MockStatisticsRepository_GetPRStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetPRStatistics_Call) Return(pRStatss []*model.PRStats, err error) *MockStatisticsRepository_GetPRStatistics_Call {
	_c.Call.Return(pRStatss, err)
	return _c
}

func (_c *MockStatisticsRepository_GetPRStatistics_Call) RunAndReturn(run func(ctx context.Context) ([]*model.PRStats, error)) *MockStatisticsRepository_GetPRStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewerStatistics provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetReviewerStatistics(ctx context.Context) ([]*model.ReviewerStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewerStatistics")
	}

	var r0 []*model.ReviewerStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.ReviewerStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.ReviewerStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ReviewerStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetReviewerStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewerStatistics'
type MockStatisticsRepository_GetReviewerStatistics_Call struct {
	*mock.Call
}

// GetReviewerStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatisticsRepository_Expecter) GetReviewerStatistics(ctx interface{}) *MockStatisticsRepository_GetReviewerStatistics_Call {
	return &MockStatisticsRepository_GetReviewerStatistics_Call{Call: _e.mock.On("GetReviewerStatistics", ctx)}
}

func (_c *MockStatisticsRepository_GetReviewerStatistics_Call) Run(run func(ctx context.Context)) *MockStatisticsRepository_GetReviewerStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetReviewerStatistics_Call) Return(reviewerStatss []*model.ReviewerStats, err error) *MockStatisticsRepository_GetReviewerStatistics_Call {
	_c.Call.Return(reviewerStatss, err)
	return _c
}

func (_c *MockStatisticsRepository_GetReviewerStatistics_Call) RunAndReturn(run func(ctx context.Context) ([]*model.ReviewerStats, error)) *MockStatisticsRepository_GetReviewerStatistics_Call {
	_c.Call.Return(run)
	return _c
}
