// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// CreateMembers provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) CreateMembers(ctx context.Context, t *model.Team) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for CreateMembers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Team) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_CreateMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMembers'
type MockTeamRepository_CreateMembers_Call struct {
	*mock.Call
}

// CreateMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - t *model.Team
func (_e *MockTeamRepository_Expecter) CreateMembers(ctx interface{}, t interface{}) *MockTeamRepository_CreateMembers_Call {
	return &MockTeamRepository_CreateMembers_Call{Call: _e.mock.On("CreateMembers", ctx, t)}
}

func (_c *MockTeamRepository_CreateMembers_Call) Run(run func(ctx context.Context, t *model.Team)) *MockTeamRepository_CreateMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Team
		if args[1] != nil {
			arg1 = args[1].(*model.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_CreateMembers_Call) Return(err error) *MockTeamRepository_CreateMembers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_CreateMembers_Call) RunAndReturn(run func(ctx context.Context, t *model.Team) error) *MockTeamRepository_CreateMembers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) CreateTeam(ctx context.Context, teamName string) error {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamRepository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamRepository_Expecter) CreateTeam(ctx interface{}, teamName interface{}) *MockTeamRepository_CreateTeam_Call {
	return &MockTeamRepository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, teamName)}
}

func (_c *MockTeamRepository_CreateTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_CreateTeam_Call) Return(err error) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_CreateTeam_Call) RunAndReturn(run func(ctx context.Context, teamName string) error) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByName provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetTeamByName(ctx context.Context, name string) (*model.Team, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 *model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Team, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Team); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByName'
type MockTeamRepository_GetTeamByName_Call struct {
	*mock.Call
}

// GetTeamByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) GetTeamByName(ctx interface{}, name interface{}) *MockTeamRepository_GetTeamByName_Call {
	return &MockTeamRepository_GetTeamByName_Call{Call: _e.mock.On("GetTeamByName", ctx, name)}
}

func (_c *MockTeamRepository_GetTeamByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamByName_Call) Return(team *model.Team, err error) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetTeamByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Team, error)) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamIDByName provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetTeamIDByName(ctx context.Context, name string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamIDByName")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetTeamIDByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamIDByName'
type MockTeamRepository_GetTeamIDByName_Call struct {
	*mock.Call
}

// GetTeamIDByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) GetTeamIDByName(ctx interface{}, name interface{}) *MockTeamRepository_GetTeamIDByName_Call {
	return &MockTeamRepository_GetTeamIDByName_Call{Call: _e.mock.On("GetTeamIDByName", ctx, name)}
}

func (_c *MockTeamRepository_GetTeamIDByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_GetTeamIDByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamIDByName_Call) Return(uUID uuid.UUID, err error) *MockTeamRepository_GetTeamIDByName_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockTeamRepository_GetTeamIDByName_Call) RunAndReturn(run func(ctx context.Context, name string) (uuid.UUID, error)) *MockTeamRepository_GetTeamIDByName_Call {
	_c.Call.Return(run)
	return _c
}
