// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTeamService
func (_mock *MockTeamService) Create(ctx context.Context, t *model.Team) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Team) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *model.Team
func (_e *MockTeamService_Expecter) Create(ctx interface{}, t interface{}) *MockTeamService_Create_Call {
	return &MockTeamService_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTeamService_Create_Call) Run(run func(ctx context.Context, t *model.Team)) *MockTeamService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Team
		if args[1] != nil {
			arg1 = args[1].(*model.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamService_Create_Call) Return(err error) *MockTeamService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamService_Create_Call) RunAndReturn(run func(ctx context.Context, t *model.Team) error) *MockTeamService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByName provides a mock function for the type MockTeamService
func (_mock *MockTeamService) GetTeamByName(ctx context.Context, name string) (*model.Team, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 *model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Team, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Team); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_GetTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByName'
type MockTeamService_GetTeamByName_Call struct {
	*mock.Call
}

// GetTeamByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamService_Expecter) GetTeamByName(ctx interface{}, name interface{}) *MockTeamService_GetTeamByName_Call {
	return &MockTeamService_GetTeamByName_Call{Call: _e.mock.On("GetTeamByName", ctx, name)}
}

func (_c *MockTeamService_GetTeamByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamService_GetTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamService_GetTeamByName_Call) Return(team *model.Team, err error) *MockTeamService_GetTeamByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamService_GetTeamByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Team, error)) *MockTeamService_GetTeamByName_Call {
	_c.Call.Return(run)
	return _c
}
