// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/client/db"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// ReadCommited provides a mock function for the type MockTxManager
func (_mock *MockTxManager) ReadCommited(ctx context.Context, f db.Handler) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for ReadCommited")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Handler) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_ReadCommited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCommited'
type MockTxManager_ReadCommited_Call struct {
	*mock.Call
}

// ReadCommited is a helper method to define mock.On call
//   - ctx context.Context
//   - f db.Handler
func (_e *MockTxManager_Expecter) ReadCommited(ctx interface{}, f interface{}) *MockTxManager_ReadCommited_Call {
	return &MockTxManager_ReadCommited_Call{Call: _e.mock.On("ReadCommited", ctx, f)}
}

func (_c *MockTxManager_ReadCommited_Call) Run(run func(ctx context.Context, f db.Handler)) *MockTxManager_ReadCommited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.Handler
		if args[1] != nil {
			arg1 = args[1].(db.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_ReadCommited_Call) Return(err error) *MockTxManager_ReadCommited_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_ReadCommited_Call) RunAndReturn(run func(ctx context.Context, f db.Handler) error) *MockTxManager_ReadCommited_Call {
	_c.Call.Return(run)
	return _c
}
