// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// SetActive provides a mock function for the type MockUserService
func (_mock *MockUserService) SetActive(ctx context.Context, req *model.UserSetActive) (*model.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserSetActive) (*model.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserSetActive) *model.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UserSetActive) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockUserService_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.UserSetActive
func (_e *MockUserService_Expecter) SetActive(ctx interface{}, req interface{}) *MockUserService_SetActive_Call {
	return &MockUserService_SetActive_Call{Call: _e.mock.On("SetActive", ctx, req)}
}

func (_c *MockUserService_SetActive_Call) Run(run func(ctx context.Context, req *model.UserSetActive)) *MockUserService_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserSetActive
		if args[1] != nil {
			arg1 = args[1].(*model.UserSetActive)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_SetActive_Call) Return(user *model.User, err error) *MockUserService_SetActive_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_SetActive_Call) RunAndReturn(run func(ctx context.Context, req *model.UserSetActive) (*model.User, error)) *MockUserService_SetActive_Call {
	_c.Call.Return(run)
	return _c
}
