// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"PR/internal/model"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetActiveByTeam provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetActiveByTeam(ctx context.Context, teamName string) ([]*model.User, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByTeam")
	}

	var r0 []*model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.User, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.User); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetActiveByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByTeam'
type MockUserRepository_GetActiveByTeam_Call struct {
	*mock.Call
}

// GetActiveByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockUserRepository_Expecter) GetActiveByTeam(ctx interface{}, teamName interface{}) *MockUserRepository_GetActiveByTeam_Call {
	return &MockUserRepository_GetActiveByTeam_Call{Call: _e.mock.On("GetActiveByTeam", ctx, teamName)}
}

func (_c *MockUserRepository_GetActiveByTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockUserRepository_GetActiveByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetActiveByTeam_Call) Return(users []*model.User, err error) *MockUserRepository_GetActiveByTeam_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetActiveByTeam_Call) RunAndReturn(run func(ctx context.Context, teamName string) ([]*model.User, error)) *MockUserRepository_GetActiveByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(user *model.User, err error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetActive(ctx context.Context, req *model.UserSetActive) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserSetActive) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockUserRepository_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.UserSetActive
func (_e *MockUserRepository_Expecter) SetActive(ctx interface{}, req interface{}) *MockUserRepository_SetActive_Call {
	return &MockUserRepository_SetActive_Call{Call: _e.mock.On("SetActive", ctx, req)}
}

func (_c *MockUserRepository_SetActive_Call) Run(run func(ctx context.Context, req *model.UserSetActive)) *MockUserRepository_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserSetActive
		if args[1] != nil {
			arg1 = args[1].(*model.UserSetActive)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_SetActive_Call) Return(err error) *MockUserRepository_SetActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetActive_Call) RunAndReturn(run func(ctx context.Context, req *model.UserSetActive) error) *MockUserRepository_SetActive_Call {
	_c.Call.Return(run)
	return _c
}
